name: CoolLib2 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Run Unit Tests

    runs-on: macos-15
    
    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set Xcode Version
        run: |
          xcodebuild -version
          sudo xcode-select -s /Applications/Xcode_16.app


      - name: Run Unit Tests
        run: |
          xcodebuild test \
            -project CoolLib2.xcodeproj \
            -scheme CoolLib2 \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -testPlan CoolLib2 \
            -derivedDataPath Build/ \
            CODE_SIGNING_ALLOWED=NO \
            COMPILER_INDEX_STORE_ENABLE=NO

      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-test-results
          path: Build/Logs/Test/*.xcresult
